services:

  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
    ports:
      - "443:443"
      - "8080:8080" # optional: local dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/cert.pem:/certs/cert.pem:ro
      - ./traefik/key.pem:/certs/key.pem:ro
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"

      # HTTPS router for website
      - "traefik.http.routers.nginx.rule=Host(`group6.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

      # HTTPS router for dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
    networks:
      - web

networks:
  web:
    driver: bridge
